[project]
name = "DbgGui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cmake>=3.31.2",
    "conan>=2.0",
    "meson>=1.5.2",
]
